//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Add_on_Product_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Add_on_Product_Master()
        {
            this.Add_On_Product_Detail = new HashSet<Add_On_Product_Detail>();
            this.SPA_INVOICE_Detail = new HashSet<SPA_INVOICE_Detail>();
        }
    
        public long Add_On_Pid { get; set; }
        public string ProductName { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public System.DateTime Updation_Date { get; set; }
        public string ActiveStatus { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field4 { get; set; }
        public string Field3 { get; set; }
        public Nullable<long> schlId { get; set; }
        public string Manufacturer { get; set; }
        public string Dozes { get; set; }
        public Nullable<long> Insurance_Id { get; set; }
        public Nullable<double> VAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Add_On_Product_Detail> Add_On_Product_Detail { get; set; }
        public virtual Health_Insurance Health_Insurance { get; set; }
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_INVOICE_Detail> SPA_INVOICE_Detail { get; set; }
    }
}
