//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_UserAnserDetails
    {
        public long AppUserAnserDetails { get; set; }
        public long UserID { get; set; }
        public long QuestionMasterID { get; set; }
        public Nullable<long> AnswerDetailsId { get; set; }
        public string AnswerDesc { get; set; }
        public string ActiveStatus { get; set; }
        public long Schid { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
