//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_AnwserDetails
    {
        public long AnserDetailsID { get; set; }
        public string Answer { get; set; }
        public long Schid { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Activestatus { get; set; }
        public long QuestionMasterId { get; set; }
        public Nullable<int> ListOrder { get; set; }
        public string Type { get; set; }
    }
}
