//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_QuestionMaster
    {
        public long QuestionMasterID { get; set; }
        public string Question { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long Schid { get; set; }
        public long AnswerTypeId { get; set; }
        public Nullable<int> ListOrder { get; set; }
    }
}
