//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_AcademicYear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CCTSP_AcademicYear()
        {
            this.CCTSP_SchedulerMaster = new HashSet<CCTSP_SchedulerMaster>();
            this.SPA_EmployeeSchedulers = new HashSet<SPA_EmployeeSchedulers>();
            this.CTSP_SolutionMaster = new HashSet<CTSP_SolutionMaster>();
        }
    
        public long AcdYearId { get; set; }
        public string AcdYearName { get; set; }
        public string AcdStartDate { get; set; }
        public string AcdEndDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_SchedulerMaster> CCTSP_SchedulerMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_EmployeeSchedulers> SPA_EmployeeSchedulers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTSP_SolutionMaster> CTSP_SolutionMaster { get; set; }
    }
}
