//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_GradeRule
    {
        public long GradeId { get; set; }
        public Nullable<long> GradeRuleId { get; set; }
        public string Grade { get; set; }
        public Nullable<decimal> MarksFrom { get; set; }
        public Nullable<decimal> MarksTo { get; set; }
        public string PassMark { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
