//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_ValueAddedServiceDetails
    {
        public long ValueAddedServiceDetailsId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailId { get; set; }
        public long Vtype { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
        public long Schid { get; set; }
        public long SentBy { get; set; }
        public string Description { get; set; }
        public string Module { get; set; }
        public Nullable<long> VmasterId { get; set; }
        public string SentStatus { get; set; }
        public string Remarks { get; set; }
    }
}
