//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_EmployeeCurrentDetails
    {
        public long EmployeeCurrentdetailId { get; set; }
        public long SchId { get; set; }
        public long EmployeeId { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<System.DateTime> DateOfLeaving { get; set; }
        public Nullable<long> MaxPeriod { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<long> Classteacher_ClassSectionId { get; set; }
        public Nullable<int> SchedulerIncharge { get; set; }
        public Nullable<int> FeeIncharge { get; set; }
        public Nullable<int> ExamIncharge { get; set; }
        public Nullable<long> AcdYearId { get; set; }
        public Nullable<int> EditProfile { get; set; }
        public long Designation { get; set; }
    }
}
