//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_TaxDetails
    {
        public long TaxID { get; set; }
        public long PaymentType { get; set; }
        public string InstrumentNo { get; set; }
        public string InstrumentName { get; set; }
        public Nullable<System.DateTime> InstrumentDate { get; set; }
        public decimal Amount { get; set; }
        public string TaxCode { get; set; }
        public string TaxStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
        public long Schid { get; set; }
        public Nullable<long> AvailMasterID { get; set; }
        public long AcdYearID { get; set; }
    }
}
