//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_AttendenceDetails
    {
        public long AttenednceDetailId { get; set; }
        public long SchId { get; set; }
        public long AttendenceMasterId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> StudentId { get; set; }
        public string FirstAttendence { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> PerformanceDetail { get; set; }
        public string MemberTStatus { get; set; }
        public string MemberAttStatsu { get; set; }
        public Nullable<long> MemberTotalPresent { get; set; }
        public Nullable<long> MemberTotalAbsent { get; set; }
        public Nullable<long> B1 { get; set; }
        public string B2 { get; set; }
    }
}
