//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_UserB
    {
        public long UserId { get; set; }
        public long SchId { get; set; }
        public long RoleId { get; set; }
        public Nullable<long> ClassSecId { get; set; }
        public Nullable<long> CCTSP_UserId { get; set; }
        public string LoginName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string PasswordQuerry1 { get; set; }
        public string Answer1 { get; set; }
        public string PasswordQuerry2 { get; set; }
        public string Answer2 { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string EmailId { get; set; }
        public string AltEmailId { get; set; }
        public string PhoneNo { get; set; }
        public string Gender { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<int> Pincode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdateStatus { get; set; }
    }
}
