//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_AnswerDetails
    {
        public long AnswerDetailsId { get; set; }
        public long SchId { get; set; }
        public long ClassSecId { get; set; }
        public Nullable<long> ExamAnswerMasterId { get; set; }
        public Nullable<long> ExamQuestionMasterId { get; set; }
        public long StudentAnswerMasterId { get; set; }
        public long UserId { get; set; }
        public Nullable<int> Marks { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string SubjectiveAnswer { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
    }
}
