//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_CategoryDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CCTSP_CategoryDetails()
        {
            this.SPA_INVOICE_Detail = new HashSet<SPA_INVOICE_Detail>();
            this.CCTSP_GroupProductDetails = new HashSet<CCTSP_GroupProductDetails>();
            this.CCTSP_GroupProductDetails1 = new HashSet<CCTSP_GroupProductDetails>();
            this.CCTSP_GroupProductDetails2 = new HashSet<CCTSP_GroupProductDetails>();
            this.CTSP_SolutionMaster = new HashSet<CTSP_SolutionMaster>();
            this.CCTSP_SchoolMaster = new HashSet<CCTSP_SchoolMaster>();
            this.spa_CustomerFeedback = new HashSet<spa_CustomerFeedback>();
            this.Prescription_Detail = new HashSet<Prescription_Detail>();
            this.Spa_BookingDetails = new HashSet<Spa_BookingDetails>();
            this.SPA_EmployeeScheduler = new HashSet<SPA_EmployeeScheduler>();
        }
    
        public long CatgTypeId { get; set; }
        public long CatgId { get; set; }
        public string CatgType { get; set; }
        public string CatgDesc { get; set; }
        public Nullable<long> Value { get; set; }
        public Nullable<int> DomainType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<int> Lang_Id { get; set; }
        public string Gender { get; set; }
        public Nullable<long> Group_orderdata { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<long> Work_Flow_Id { get; set; }
        public string Banner_Image { get; set; }
        public string Search_Image { get; set; }
        public string Email_Image { get; set; }
        public Nullable<long> Insurance_Id { get; set; }
        public Nullable<double> VAT { get; set; }
    
        public virtual Health_Insurance Health_Insurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_INVOICE_Detail> SPA_INVOICE_Detail { get; set; }
        public virtual CCTSP_CategoryMaster CCTSP_CategoryMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_GroupProductDetails> CCTSP_GroupProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_GroupProductDetails> CCTSP_GroupProductDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_GroupProductDetails> CCTSP_GroupProductDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTSP_SolutionMaster> CTSP_SolutionMaster { get; set; }
        public virtual Language_Master Language_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_SchoolMaster> CCTSP_SchoolMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spa_CustomerFeedback> spa_CustomerFeedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription_Detail> Prescription_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spa_BookingDetails> Spa_BookingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_EmployeeScheduler> SPA_EmployeeScheduler { get; set; }
    }
}
