//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_FeeSecurityDeposit
    {
        public long FeeSecurityDeposit { get; set; }
        public long FeeHead { get; set; }
        public decimal Amount { get; set; }
        public Nullable<long> PaymentType { get; set; }
        public Nullable<long> Payment { get; set; }
        public Nullable<System.DateTime> Refunddate { get; set; }
        public Nullable<long> RefundPaymentType { get; set; }
        public long Student { get; set; }
        public string Bankdetails { get; set; }
        public Nullable<long> FeeMaster_masterId { get; set; }
        public string StudentStatus { get; set; }
    }
}
