//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_FeeRuleClassSection
    {
        public long FeeSecId { get; set; }
        public long SchId { get; set; }
        public long ClassSecId { get; set; }
        public long CollectionType { get; set; }
        public decimal Amount { get; set; }
        public long FeeHeadId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Activestatus { get; set; }
        public Nullable<long> GroupId { get; set; }
    }
}
