//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_LendingPageMaster
    {
        public long LendingPage_Id { get; set; }
        public string Logo { get; set; }
        public string Logotext { get; set; }
        public string ShopName { get; set; }
        public string Logotext_Color { get; set; }
        public string Shopimg1 { get; set; }
        public string Shopimg2 { get; set; }
        public string Shopimg3 { get; set; }
        public string Shopimg4 { get; set; }
        public Nullable<long> Schid { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public string Field4 { get; set; }
        public string Field5 { get; set; }
        public string Original_Website { get; set; }
        public string Azure_Website { get; set; }
        public string ServerName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Registered_Version { get; set; }
        public Nullable<System.DateTime> Registered_Date { get; set; }
        public string Display_Marketing { get; set; }
        public string FromDay { get; set; }
        public string ToDay { get; set; }
        public string ShopStartTime { get; set; }
        public string ShopEndTime { get; set; }
        public string Address { get; set; }
        public string Email_id { get; set; }
        public string PhoneNo { get; set; }
        public string ZipCode { get; set; }
        public string ShopCity { get; set; }
        public string ShopDesc { get; set; }
    
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster { get; set; }
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster1 { get; set; }
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster2 { get; set; }
    }
}
