//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_Validation
    {
        public long ValidationId { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public string Verified { get; set; }
    }
}
