//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_FeeCollectionDetails
    {
        public long detailsID { get; set; }
        public long CollMasterID { get; set; }
        public long FeeHead { get; set; }
        public long AmountTye { get; set; }
        public decimal Amount { get; set; }
        public string RecStatus { get; set; }
        public long FeeType { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
    }
}
