//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_ItemMaster
    {
        public long ItemID { get; set; }
        public long ItemTypeCatID { get; set; }
        public long ItemNameCatgID { get; set; }
        public long UnitCatgId { get; set; }
        public long IssueSalesType { get; set; }
        public string Size { get; set; }
        public Nullable<long> ClassSecID { get; set; }
        public string Image { get; set; }
        public Nullable<long> StoreCatgId { get; set; }
        public Nullable<long> StoreInchargeUserID { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public string RecordStatus { get; set; }
        public long SchID { get; set; }
        public long AcdYear { get; set; }
        public Nullable<decimal> SaleTax { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public string ItemCode { get; set; }
        public string ItemDesc { get; set; }
    }
}
