//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_TransportRouteDetails
    {
        public long TransportDetailsId { get; set; }
        public long UserId { get; set; }
        public long SchId { get; set; }
        public long RouteCatgId { get; set; }
        public string BusStopName { get; set; }
        public Nullable<System.TimeSpan> PickUpTime { get; set; }
        public Nullable<System.TimeSpan> DropTime { get; set; }
        public string BusNo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<decimal> PicCharges { get; set; }
        public Nullable<decimal> DropCharges { get; set; }
    }
}
