//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_BookIssueRegister
    {
        public long SlNo { get; set; }
        public long UserId { get; set; }
        public long AccessionNo { get; set; }
        public long SchId { get; set; }
        public System.DateTime Issuedate { get; set; }
        public Nullable<System.DateTime> ExpectedReturndate { get; set; }
        public Nullable<System.DateTime> Actualreturndate { get; set; }
        public Nullable<int> Duration { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<decimal> Actualfineamount { get; set; }
        public string Activestatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
