//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_ABC
    {
        public long SolutionId { get; set; }
        public long CatgTypeId { get; set; }
        public string SectionName { get; set; }
        public string SectionDesc { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> CraetedOn { get; set; }
        public string Activestatus { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> AcdYearId { get; set; }
        public Nullable<long> SchId { get; set; }
        public string Group { get; set; }
        public Nullable<long> MemberShipCatgID { get; set; }
        public Nullable<long> ActivityID { get; set; }
    }
}
