//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_SchoolMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CCTSP_SchoolMaster()
        {
            this.Add_On_Product_Detail = new HashSet<Add_On_Product_Detail>();
            this.Add_on_Product_Master = new HashSet<Add_on_Product_Master>();
            this.Assigned_Health_Insurance = new HashSet<Assigned_Health_Insurance>();
            this.CCTSP_GroupProductDetails = new HashSet<CCTSP_GroupProductDetails>();
            this.CCTSP_LendingPageMaster = new HashSet<CCTSP_LendingPageMaster>();
            this.CCTSP_LendingPageMaster1 = new HashSet<CCTSP_LendingPageMaster>();
            this.CCTSP_LendingPageMaster2 = new HashSet<CCTSP_LendingPageMaster>();
            this.cctsp_RoleDetails = new HashSet<cctsp_RoleDetails>();
            this.CCTSP_SchedulerMaster = new HashSet<CCTSP_SchedulerMaster>();
            this.Invoice_Master = new HashSet<Invoice_Master>();
            this.SPA_INVOICE_MASTER = new HashSet<SPA_INVOICE_MASTER>();
            this.SPA_INVOICE_Detail = new HashSet<SPA_INVOICE_Detail>();
            this.spa_BillingDetails = new HashSet<spa_BillingDetails>();
            this.spa_BillingMaster = new HashSet<spa_BillingMaster>();
            this.CCTSP_UserDetail = new HashSet<CCTSP_UserDetail>();
            this.Marketing_Master = new HashSet<Marketing_Master>();
            this.Marketing_SendHistory = new HashSet<Marketing_SendHistory>();
            this.spa_Master_Reservation = new HashSet<spa_Master_Reservation>();
            this.spa_contact = new HashSet<spa_contact>();
            this.CCTSP_User = new HashSet<CCTSP_User>();
            this.SPA_EmployeeSchedulers = new HashSet<SPA_EmployeeSchedulers>();
            this.Spa_BookingDetails = new HashSet<Spa_BookingDetails>();
            this.Medicine_Master = new HashSet<Medicine_Master>();
            this.Prescription_Master = new HashSet<Prescription_Master>();
            this.Prescription_Detail = new HashSet<Prescription_Detail>();
            this.CTSP_SolutionMaster = new HashSet<CTSP_SolutionMaster>();
            this.SPA_EmployeeScheduler = new HashSet<SPA_EmployeeScheduler>();
            this.SPA_SchedulerSlotMaster = new HashSet<SPA_SchedulerSlotMaster>();
            this.SPA_UserDetail = new HashSet<SPA_UserDetail>();
        }
    
        public long SchlId { get; set; }
        public string SchlName { get; set; }
        public string SchlLandline1 { get; set; }
        public string SchlLandline2 { get; set; }
        public string SchlMobile1 { get; set; }
        public string SchlMobile2 { get; set; }
        public string SchlFax1 { get; set; }
        public string SchlFax2 { get; set; }
        public string SchlEmail { get; set; }
        public string SchlWebsite { get; set; }
        public string SchlBranchCode { get; set; }
        public string SchlGroupName { get; set; }
        public string SchlAddress { get; set; }
        public string SchlCity { get; set; }
        public string SchlState { get; set; }
        public string SchPin { get; set; }
        public string SchlEstd { get; set; }
        public Nullable<int> SchlEmployeeStrength { get; set; }
        public Nullable<int> SchlStudentStrength { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<long> ClientState { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<decimal> DealAmount { get; set; }
        public string DeliveryStatus { get; set; }
        public Nullable<long> Owner_UserID { get; set; }
        public Nullable<long> MainCategory { get; set; }
        public string SHOPTYPE { get; set; }
        public Nullable<long> CUSTOMERNO { get; set; }
        public string ImageLogo { get; set; }
        public string BANKNAME { get; set; }
        public string BANKACCOUNT { get; set; }
        public string IBANNO { get; set; }
        public Nullable<int> Lang_id { get; set; }
        public Nullable<int> AlertRemainder { get; set; }
        public Nullable<int> AdvBookingRestrict { get; set; }
        public string Currency { get; set; }
        public string BookingApproval { get; set; }
        public string send_sms { get; set; }
        public Nullable<long> total_sms { get; set; }
        public Nullable<long> total_email { get; set; }
        public Nullable<long> Color_Id { get; set; }
        public string Schcountry { get; set; }
        public string TimeZone { get; set; }
        public Nullable<int> timezone_id { get; set; }
        public string Terms_conditions { get; set; }
        public string HostingProvider { get; set; }
        public string Hosting_UserName { get; set; }
        public string Hosting_Password { get; set; }
        public Nullable<int> ShowPrice { get; set; }
        public string flgWebsite { get; set; }
        public string is_publish { get; set; }
        public string jsonModel { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string location { get; set; }
        public Nullable<int> TrialPeriod { get; set; }
        public Nullable<int> is_trial { get; set; }
        public string PaymentType { get; set; }
        public Nullable<int> Is_FreeCustomer { get; set; }
        public Nullable<int> Display_FreeCustomer { get; set; }
        public string Vat { get; set; }
        public string VatNumber { get; set; }
        public Nullable<int> OverDue { get; set; }
        public string StreetNumber { get; set; }
        public Nullable<int> Display_Invoice { get; set; }
        public string street { get; set; }
        public Nullable<int> ExpCustlink { get; set; }
        public Nullable<int> Extend_Pay_Duration { get; set; }
        public Nullable<int> Cancel_Res_Duration { get; set; }
        public string Post_number { get; set; }
        public Nullable<int> Is_HealthInsurance { get; set; }
        public string Invoice_FreeText { get; set; }
        public string TimeSlot { get; set; }
        public Nullable<long> Flow_Id { get; set; }
        public string Invoice_Email_Txt { get; set; }
        public bool AllOW_PastDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Add_On_Product_Detail> Add_On_Product_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Add_on_Product_Master> Add_on_Product_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assigned_Health_Insurance> Assigned_Health_Insurance { get; set; }
        public virtual CCTSP_CategoryDetails CCTSP_CategoryDetails { get; set; }
        public virtual CCTSP_ColorMaster CCTSP_ColorMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_GroupProductDetails> CCTSP_GroupProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_LendingPageMaster> CCTSP_LendingPageMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_LendingPageMaster> CCTSP_LendingPageMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_LendingPageMaster> CCTSP_LendingPageMaster2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cctsp_RoleDetails> cctsp_RoleDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_SchedulerMaster> CCTSP_SchedulerMaster { get; set; }
        public virtual Language_Master Language_Master { get; set; }
        public virtual Language_Master Language_Master1 { get; set; }
        public virtual spatime_zone spatime_zone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Master> Invoice_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_INVOICE_MASTER> SPA_INVOICE_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_INVOICE_Detail> SPA_INVOICE_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spa_BillingDetails> spa_BillingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spa_BillingMaster> spa_BillingMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_UserDetail> CCTSP_UserDetail { get; set; }
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster1 { get; set; }
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster2 { get; set; }
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster11 { get; set; }
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster3 { get; set; }
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster12 { get; set; }
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marketing_Master> Marketing_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marketing_SendHistory> Marketing_SendHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spa_Master_Reservation> spa_Master_Reservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spa_contact> spa_contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_User> CCTSP_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_EmployeeSchedulers> SPA_EmployeeSchedulers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spa_BookingDetails> Spa_BookingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicine_Master> Medicine_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription_Master> Prescription_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription_Detail> Prescription_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTSP_SolutionMaster> CTSP_SolutionMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_EmployeeScheduler> SPA_EmployeeScheduler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_SchedulerSlotMaster> SPA_SchedulerSlotMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_UserDetail> SPA_UserDetail { get; set; }
        public virtual CCTSP_User CCTSP_User1 { get; set; }
    }
}
