//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_ProductDetails
    {
        public long ProductDetailsId { get; set; }
        public long ProductMasterId { get; set; }
        public string ShortName { get; set; }
        public string Feature { get; set; }
        public Nullable<long> PIdRowSpan { get; set; }
        public Nullable<long> PIdColumnSpan { get; set; }
        public Nullable<long> ShortRowSpan { get; set; }
        public Nullable<long> ShortColumnSpan { get; set; }
        public Nullable<long> FeatureRowSpan { get; set; }
        public Nullable<long> FeatureColumnSpan { get; set; }
        public Nullable<int> Groupid { get; set; }
        public Nullable<int> OredrBy { get; set; }
    }
}
