//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_AssgnmentHomeworkMarksDetails
    {
        public long AssignmentHwMarksId { get; set; }
        public long SchId { get; set; }
        public Nullable<long> LessonProgressId { get; set; }
        public long StudentId { get; set; }
        public string Type { get; set; }
        public int MarksOptained { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
    }
}
