//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class cctsp_Timezone
    {
        public long TimeZone_Id { get; set; }
        public string Timezone { get; set; }
        public string Country { get; set; }
        public string UTC { get; set; }
        public Nullable<int> UTC_Hour { get; set; }
        public Nullable<int> UTC_Minutes { get; set; }
    }
}
