//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class cctsp_SecureIdentity
    {
        public long IdentityDetaisId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string IdAddress { get; set; }
        public string MacAddress { get; set; }
        public string OtherDetails { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long Schid { get; set; }
    }
}
