//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_ClassSubjectDetails
    {
        public long SubjId { get; set; }
        public long SchId { get; set; }
        public long ClassSecId { get; set; }
        public long SubCatId { get; set; }
        public string Comp_optional { get; set; }
        public Nullable<int> MaxPeriod { get; set; }
        public Nullable<long> TotalNoOfTopics { get; set; }
        public Nullable<long> TotalNoOfPeriodPerWeek { get; set; }
        public string Scholastic_CoScholastic { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<long> AcdYearId { get; set; }
        public Nullable<long> TeacherId { get; set; }
        public Nullable<long> BatchId { get; set; }
        public Nullable<decimal> ActivityAmount { get; set; }
    }
}
