//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_ItemIssueSaleMaster
    {
        public long ItemISMId { get; set; }
        public Nullable<long> CustomerUserId { get; set; }
        public Nullable<long> IssueSaleType { get; set; }
        public string IssueRecieptNo { get; set; }
        public string SalesRecieptNo { get; set; }
        public System.DateTime Sale_IssueDate { get; set; }
        public Nullable<decimal> SaleTax { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> OtherCharges { get; set; }
        public Nullable<decimal> TotalDiscountAmount { get; set; }
        public Nullable<decimal> TotalCharges { get; set; }
        public Nullable<decimal> ActualAmountReciept { get; set; }
        public Nullable<decimal> BalanceAmountTobePaid { get; set; }
        public Nullable<System.DateTime> ExpectedReturndate { get; set; }
        public long TransBy { get; set; }
        public string FeedBackRemarks { get; set; }
        public Nullable<long> SchId { get; set; }
        public Nullable<long> AcdYear { get; set; }
        public string RecordStatus { get; set; }
    }
}
