//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_HealthDetails
    {
        public long UserHealthId { get; set; }
        public long SchId { get; set; }
        public long UserId { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<int> Height_inCM { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string LeftEyeSide { get; set; }
        public string RightEyeSide { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
    }
}
