//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_StudentCurrentDetails
    {
        public long StudentCurrentDetailsId { get; set; }
        public long SchId { get; set; }
        public Nullable<long> StudentId { get; set; }
        public long ClassSecId { get; set; }
        public long AcdYearId { get; set; }
        public Nullable<int> RollNo { get; set; }
        public System.DateTime AdmissonDate { get; set; }
        public string AdmissonNo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<decimal> OpeningBal { get; set; }
        public Nullable<decimal> CloseingBal { get; set; }
        public Nullable<long> FeeInstallType { get; set; }
        public Nullable<long> GroupCatgId { get; set; }
        public Nullable<long> CatgId { get; set; }
        public Nullable<long> TransportRouteId { get; set; }
        public string TransportFlag { get; set; }
    }
}
