//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_SchedulerMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CCTSP_SchedulerMaster()
        {
            this.SPA_EmployeeSchedulers = new HashSet<SPA_EmployeeSchedulers>();
            this.SPA_EmployeeScheduler = new HashSet<SPA_EmployeeScheduler>();
            this.SPA_SchedulerSlotMaster = new HashSet<SPA_SchedulerSlotMaster>();
        }
    
        public long SchedulerId { get; set; }
        public long SchId { get; set; }
        public string WeekDay { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> PeriodNumber { get; set; }
        public string PeriodType { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<long> AcdYearId { get; set; }
    
        public virtual CCTSP_AcademicYear CCTSP_AcademicYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_EmployeeSchedulers> SPA_EmployeeSchedulers { get; set; }
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_EmployeeScheduler> SPA_EmployeeScheduler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_SchedulerSlotMaster> SPA_SchedulerSlotMaster { get; set; }
    }
}
