//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_ExamMaster
    {
        public long ExamId { get; set; }
        public long ExamCatID { get; set; }
        public Nullable<long> CyclecatgId { get; set; }
        public Nullable<decimal> MaxMarks { get; set; }
        public Nullable<decimal> PassMarks { get; set; }
        public string CurrentStatus { get; set; }
        public string ActiveStatus { get; set; }
        public long SchId { get; set; }
        public long AcdYear { get; set; }
        public Nullable<long> ClassSection { get; set; }
    }
}
