//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_FeeCollectionMaster
    {
        public long MasterId { get; set; }
        public long StudentId { get; set; }
        public Nullable<long> FeeCollRecieptNo { get; set; }
        public long Acdyear { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long SchID { get; set; }
        public string TempRecieptNo { get; set; }
        public decimal Installmentamount { get; set; }
        public Nullable<long> InstallmentId { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> RecieptAdjAmount { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public string DefaulterStatus { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> FineAmount { get; set; }
    }
}
