//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CCTSP_User()
        {
            this.CCTSP_SchoolMaster1 = new HashSet<CCTSP_SchoolMaster>();
            this.SPA_INVOICE_MASTER = new HashSet<SPA_INVOICE_MASTER>();
            this.SPA_INVOICE_MASTER1 = new HashSet<SPA_INVOICE_MASTER>();
            this.CCTSP_UserDetail = new HashSet<CCTSP_UserDetail>();
            this.Medicine_Master = new HashSet<Medicine_Master>();
            this.Prescription_Detail = new HashSet<Prescription_Detail>();
            this.Prescription_Master = new HashSet<Prescription_Master>();
            this.SPA_SchedulerSlotMaster = new HashSet<SPA_SchedulerSlotMaster>();
            this.SPA_UserDetail = new HashSet<SPA_UserDetail>();
            this.SPA_EmployeeSchedulers = new HashSet<SPA_EmployeeSchedulers>();
            this.CTSP_SolutionMaster1 = new HashSet<CTSP_SolutionMaster>();
            this.CCTSP_Anamnese = new HashSet<CCTSP_Anamnese>();
            this.CCTSP_Anamnese1 = new HashSet<CCTSP_Anamnese>();
        }
    
        public long UserId { get; set; }
        public long SchId { get; set; }
        public long RoleId { get; set; }
        public string LoginName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string PasswordQuerry1 { get; set; }
        public string Answer1 { get; set; }
        public string PasswordQuerry2 { get; set; }
        public string Answer2 { get; set; }
        public System.DateTime DOB { get; set; }
        public string EmailId { get; set; }
        public string AltEmailId { get; set; }
        public string PhoneNo { get; set; }
        public string Gender { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<int> Pincode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<int> update_state { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> BillingDate { get; set; }
        public Nullable<long> MembershipType { get; set; }
        public Nullable<decimal> ActualBillingAmount { get; set; }
        public Nullable<long> MemberID { get; set; }
        public Nullable<System.DateTime> AnniversaryDate { get; set; }
        public Nullable<int> BillingPeriodDiscount { get; set; }
        public Nullable<int> nint { get; set; }
        public string nvarchar2 { get; set; }
        public Nullable<decimal> ndecimal { get; set; }
        public Nullable<int> Depth { get; set; }
        public string Lineage { get; set; }
        public Nullable<int> SMS_Service { get; set; }
        public Nullable<int> Email_Service { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Other_Schid { get; set; }
        public string specialization { get; set; }
        public Nullable<int> ExperienceYear { get; set; }
        public string skypeId { get; set; }
        public string Degree { get; set; }
        public Nullable<int> ExperienceMonth { get; set; }
        public string deviceId { get; set; }
        public Nullable<int> Lang_Id { get; set; }
        public string BaseUrl { get; set; }
        public Nullable<long> Created_By { get; set; }
        public string Invoice_Service { get; set; }
        public string Salutation { get; set; }
        public string Title { get; set; }
        public string Street { get; set; }
        public string StreetNumber { get; set; }
        public string GLN_No { get; set; }
        public string ZSR_No { get; set; }
        public string AHV_Number { get; set; }
        public string VEKA_Number { get; set; }
        public string InsuranceNumber { get; set; }
        public Nullable<int> Display_Invoice { get; set; }
    
        public virtual CCTSP_Role CCTSP_Role { get; set; }
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_SchoolMaster> CCTSP_SchoolMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_INVOICE_MASTER> SPA_INVOICE_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_INVOICE_MASTER> SPA_INVOICE_MASTER1 { get; set; }
        public virtual GYM_Member_Dept GYM_Member_Dept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_UserDetail> CCTSP_UserDetail { get; set; }
        public virtual GYM_Member_Dept GYM_Member_Dept1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicine_Master> Medicine_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription_Detail> Prescription_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription_Master> Prescription_Master { get; set; }
        public virtual CTSP_SolutionMaster CTSP_SolutionMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_SchedulerSlotMaster> SPA_SchedulerSlotMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_UserDetail> SPA_UserDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_EmployeeSchedulers> SPA_EmployeeSchedulers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTSP_SolutionMaster> CTSP_SolutionMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_Anamnese> CCTSP_Anamnese { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_Anamnese> CCTSP_Anamnese1 { get; set; }
    }
}
