//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_ItemStockVerification
    {
        public long ItemStockVerficationId { get; set; }
        public Nullable<long> Itemdetailsid { get; set; }
        public int QTYVerified { get; set; }
        public Nullable<int> QTYAcceptance { get; set; }
        public Nullable<int> RejectedQty { get; set; }
        public long ItemStockdetailsID { get; set; }
        public string RejectedQtyReason { get; set; }
        public Nullable<decimal> DamagePrice { get; set; }
        public long VerifiedBy { get; set; }
        public System.DateTime VerifiedDate { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<long> ItemReturnID { get; set; }
        public long SchId { get; set; }
        public long AcdYear { get; set; }
        public string RecordStatus { get; set; }
    }
}
