//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_ItemIssueReturnDetails
    {
        public long ItemReturnId { get; set; }
        public long ItemISMDetailsID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<long> IssuedBy { get; set; }
        public string IssueStatus { get; set; }
        public long EntryBY { get; set; }
        public Nullable<long> EntryDate { get; set; }
        public long SchId { get; set; }
        public long AcdYear { get; set; }
        public string RecordStatus { get; set; }
    }
}
