//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_FeeCollectionReciept
    {
        public long Reciept { get; set; }
        public System.DateTime Recieptdate { get; set; }
        public long PaymentType { get; set; }
        public Nullable<long> Type { get; set; }
        public Nullable<int> InstrumentNo { get; set; }
        public Nullable<System.DateTime> InstrumentDate { get; set; }
        public string Name { get; set; }
        public string BankPayStatus { get; set; }
        public string Status { get; set; }
        public decimal AmountPaid { get; set; }
        public long Schid { get; set; }
        public long AcdYear { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> Invoiceno { get; set; }
        public Nullable<decimal> advance { get; set; }
        public Nullable<long> StudentId { get; set; }
    }
}
