//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class cctsp_RoleDetails
    {
        public long RoleDetailId { get; set; }
        public long RoleId { get; set; }
        public long SchId { get; set; }
        public string AccessToMenu { get; set; }
        public string AccessToSub { get; set; }
        public string AccessToData { get; set; }
        public string ModifyAccess { get; set; }
        public string insertAccess { get; set; }
        public string DeleteAccess { get; set; }
        public string UpdateAccess { get; set; }
        public string status { get; set; }
        public string DefaultLink { get; set; }
        public string field1 { get; set; }
        public string field2 { get; set; }
        public string field3 { get; set; }
        public string field4 { get; set; }
        public string ActiveStatus { get; set; }
    
        public virtual CCTSP_Role CCTSP_Role { get; set; }
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster { get; set; }
    }
}
