//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_ImageTable
    {
        public int Id { get; set; }
        public long SchlId { get; set; }
        public byte[] ImageLogo { get; set; }
        public byte[] ImageSchool1 { get; set; }
        public byte[] ImageSchool2 { get; set; }
        public byte[] ImageSchool3 { get; set; }
    }
}
