//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_ItemSalesBalance_PaymentDetails
    {
        public long ItemsalebalPayDetailsID { get; set; }
        public Nullable<long> ItemISMID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> BalanceAmtPaid { get; set; }
        public Nullable<decimal> NextBalAmtToBePaid { get; set; }
        public Nullable<System.DateTime> NextPaymentDate { get; set; }
        public string StatusClosed { get; set; }
        public string Remarks { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<long> SchId { get; set; }
        public Nullable<long> AcdYear { get; set; }
    }
}
