//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_ProductMaster
    {
        public long ProductMasterId { get; set; }
        public long CatgTypeId { get; set; }
        public string Functionality { get; set; }
        public Nullable<long> Standard { get; set; }
        public Nullable<long> Premuim { get; set; }
        public Nullable<long> Ultimate { get; set; }
        public Nullable<long> OrderBy { get; set; }
        public string Image { get; set; }
    }
}
