//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_ItemStoreInvoiceMaster
    {
        public long ItemStoreMasterId { get; set; }
        public string InvNumber { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public long SupplerID { get; set; }
        public Nullable<decimal> InvPrice { get; set; }
        public Nullable<decimal> TransportCharges { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> SaleTax { get; set; }
        public Nullable<decimal> OtherCharges { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalAmountReleased { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public Nullable<System.DateTime> ExpectedDateOfRelease { get; set; }
        public string Remarks { get; set; }
        public long SchID { get; set; }
        public long AcdYear { get; set; }
        public string RecordeStatus { get; set; }
    }
}
