//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_ValueAddedServiceMaster
    {
        public long valueAddesServiceMasterID { get; set; }
        public int MaxSMS { get; set; }
        public int TotalSent { get; set; }
        public int Failure { get; set; }
        public int LastCarried { get; set; }
        public Nullable<int> CarryForward { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ExpDate { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long Schid { get; set; }
    }
}
