//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_ItemQtyIssueDetails
    {
        public long ItemQtyIssueDetailsId { get; set; }
        public long ItemISMID { get; set; }
        public Nullable<long> ItemStoreDetailsID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<long> SchID { get; set; }
        public Nullable<long> AcdYear { get; set; }
        public string RecordStatus { get; set; }
    }
}
