//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_SubjectSyllabusDetails
    {
        public long SubjectSyllabusId { get; set; }
        public long SubCatId { get; set; }
        public long ClassCatId { get; set; }
        public long ChapterCatgId { get; set; }
        public string TopicName { get; set; }
        public Nullable<int> EstemitatedDuration { get; set; }
        public string ComFlag { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
        public long AcYear { get; set; }
    }
}
