//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_ExamQuestionMaster
    {
        public long ExamQuestionMasterId { get; set; }
        public long SchId { get; set; }
        public Nullable<long> SubjectSyllabusId { get; set; }
        public string Question { get; set; }
        public Nullable<int> Marks { get; set; }
        public long ClassCatId { get; set; }
        public long AnswerTypeId { get; set; }
        public Nullable<int> Time { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
        public long AcdYearId { get; set; }
    }
}
