//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_ItemStoreDetails
    {
        public long ItemStoredetailsId { get; set; }
        public long ItemID { get; set; }
        public Nullable<int> QTYRecived { get; set; }
        public System.DateTime QTYRecivedDate { get; set; }
        public long RecivedBy { get; set; }
        public string BatchNo { get; set; }
        public string Manufacture { get; set; }
        public Nullable<System.DateTime> Manufacturedate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public decimal UnitPrice { get; set; }
        public long ItemStoreMasterId { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<long> ItemReturnId { get; set; }
        public long SchID { get; set; }
        public long AcdYear { get; set; }
        public string RecordStatus { get; set; }
    }
}
