//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTSP_Examdetails
    {
        public long ExamDetailsId { get; set; }
        public long SchId { get; set; }
        public long ClassSecId { get; set; }
        public long ExamCatId { get; set; }
        public long SubjId { get; set; }
        public int MaxMark { get; set; }
        public int PassMark { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<long> SubSubjCatgtId { get; set; }
        public string ExamEntryType { get; set; }
        public string CurrentStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<long> MarksEnteredBy { get; set; }
        public Nullable<long> GradeRuleId { get; set; }
        public Nullable<long> ExamMasterId { get; set; }
        public Nullable<long> MainSubjCatgId { get; set; }
        public Nullable<long> AcdYear { get; set; }
    }
}
