//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTSP_SolutionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTSP_SolutionMaster()
        {
            this.CCTSP_User = new HashSet<CCTSP_User>();
        }
    
        public long SolutionId { get; set; }
        public long CatgTypeId { get; set; }
        public string SectionName { get; set; }
        public string SectionDesc { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> CraetedOn { get; set; }
        public string Activestatus { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> AcdYearId { get; set; }
        public Nullable<long> SchId { get; set; }
        public string Group { get; set; }
        public Nullable<long> MemberShipCatgID { get; set; }
        public Nullable<long> ActivityID { get; set; }
        public string ItenName { get; set; }
        public string Amount { get; set; }
        public string Duration { get; set; }
        public Nullable<long> OrderData { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Url { get; set; }
    
        public virtual CCTSP_AcademicYear CCTSP_AcademicYear { get; set; }
        public virtual CCTSP_CategoryDetails CCTSP_CategoryDetails { get; set; }
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_User> CCTSP_User { get; set; }
        public virtual CCTSP_User CCTSP_User1 { get; set; }
        public virtual GYM_DefinationMaster GYM_DefinationMaster { get; set; }
        public virtual GYM_DefinationMaster GYM_DefinationMaster1 { get; set; }
    }
}
