//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCM_Deals
    {
        public long ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> ActualPrice { get; set; }
        public Nullable<int> ValidTime { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> COnsumerEntries { get; set; }
        public string Image { get; set; }
        public string Activestatus { get; set; }
        public long CID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long SchId { get; set; }
    }
}
