//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCM_PackageDetails
    {
        public long ProductDetailsId { get; set; }
        public long ItemCatgId { get; set; }
        public decimal ActualCost { get; set; }
        public decimal Discount { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<decimal> DiscountedAmt { get; set; }
        public long PackageMasterId { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long Schid { get; set; }
        public int NOofCoupon { get; set; }
        public int Mon { get; set; }
        public int Tue { get; set; }
        public int wed { get; set; }
        public int thu { get; set; }
        public int Fri { get; set; }
        public int Sat { get; set; }
        public int Sun { get; set; }
        public string nvarcharc1 { get; set; }
    }
}
