//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCM_AvailDetails
    {
        public long AvailDetailsId { get; set; }
        public long PackageDetailsId { get; set; }
        public string AvailStatus { get; set; }
        public Nullable<System.DateTime> AvailedDate { get; set; }
        public string UniqueCode { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long AvailedMasterId { get; set; }
    }
}
