//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCm_AvailMaster
    {
        public long AvailMasterId { get; set; }
        public long UserId { get; set; }
        public long PackageMasterId { get; set; }
        public Nullable<long> ReferalCode { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long AcdYearId { get; set; }
        public long SchId { get; set; }
        public string PayType { get; set; }
        public Nullable<long> PaymentType { get; set; }
        public string ResponseCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> TaxID { get; set; }
        public string OfferCode { get; set; }
    }
}
