//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCM_ProductMaster
    {
        public long ProductMasterId { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public int NoOfItems { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public int MaxSale { get; set; }
        public Nullable<int> Sold { get; set; }
        public int PackageSalePoint { get; set; }
        public string ActiveStatus { get; set; }
        public long SchId { get; set; }
        public long AcdYearId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ClientId { get; set; }
        public string Rule { get; set; }
        public int NoofVisitPerBookLet { get; set; }
        public int ExpectedVisted { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> bigintc1 { get; set; }
        public Nullable<long> bigintc2 { get; set; }
        public string nvarcharc1 { get; set; }
        public string nvarcharc2 { get; set; }
    }
}
