//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_Record
    {
        public long Em_id { get; set; }
        public string EmailTo { get; set; }
        public string Subject { get; set; }
        public string ProjectName { get; set; }
        public string Content { get; set; }
        public string byte1 { get; set; }
        public string byte2 { get; set; }
        public string ActiveStatus { get; set; }
        public string SchId { get; set; }
        public string Field3 { get; set; }
        public string Field4 { get; set; }
        public string Field5 { get; set; }
        public string Field6 { get; set; }
        public string Field7 { get; set; }
        public string Field1 { get; set; }
    }
}
