//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GYM_DefinationMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GYM_DefinationMaster()
        {
            this.CTSP_SolutionMaster = new HashSet<CTSP_SolutionMaster>();
            this.CTSP_SolutionMaster1 = new HashSet<CTSP_SolutionMaster>();
        }
    
        public long DefinationID { get; set; }
        public string Description { get; set; }
        public Nullable<long> Type { get; set; }
        public Nullable<long> Schid { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> @int { get; set; }
        public string nvarcha2 { get; set; }
        public string nvarchar1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTSP_SolutionMaster> CTSP_SolutionMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTSP_SolutionMaster> CTSP_SolutionMaster1 { get; set; }
    }
}
