//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GYMActivityDetail
    {
        public long ActivityDetailsId { get; set; }
        public long UserID { get; set; }
        public long ActivityId { get; set; }
        public decimal Amount { get; set; }
        public long SchID { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
