//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_BookingMaster
    {
        public long BookingMAsterID { get; set; }
        public long UserId { get; set; }
        public System.DateTime Checkindate { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public Nullable<System.DateTime> BookDate { get; set; }
        public Nullable<System.DateTime> ActualCheckinDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
        public long Schid { get; set; }
        public long Acdyear { get; set; }
        public string CustomerStatus { get; set; }
        public string Renarks { get; set; }
        public int NoDays { get; set; }
        public Nullable<long> BookedThrough { get; set; }
        public Nullable<System.DateTime> ActualCheckOutDate { get; set; }
    }
}
