//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_BookingDetails
    {
        public long BookingDetails { get; set; }
        public System.DateTime CheckedInDate { get; set; }
        public string CheckinType { get; set; }
        public long RoomType { get; set; }
        public long RoomNumber { get; set; }
        public string ActiveStatus { get; set; }
        public long SchId { get; set; }
        public long Acdyear { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string BookingStatus { get; set; }
        public long BookingMasterID { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Misamount { get; set; }
        public string Remarks { get; set; }
    }
}
