//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_TaxDetails
    {
        public long TaxId { get; set; }
        public long BillID { get; set; }
        public long ServiceCatgType { get; set; }
        public decimal PerTax { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long Schid { get; set; }
        public long AcdYear { get; set; }
    }
}
