//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_ServicesDetails
    {
        public long ServicesDetailsId { get; set; }
        public int TotalUnits { get; set; }
        public decimal UnitCost { get; set; }
        public decimal TotalCost { get; set; }
        public Nullable<long> BillType { get; set; }
        public long UserId { get; set; }
        public long AcdyearId { get; set; }
        public long SchId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
        public long RoomNo { get; set; }
        public long BookMasterId { get; set; }
        public long ServiceMasterId { get; set; }
        public Nullable<long> OrderNo { get; set; }
    }
}
