//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_ServiceMaster
    {
        public long ServiceMasterId { get; set; }
        public long ServicesType { get; set; }
        public string ServiceDesc { get; set; }
        public int PerUnit { get; set; }
        public long MeasurementUnit { get; set; }
        public decimal UnitCost { get; set; }
        public string ActiveStatus { get; set; }
        public long Schid { get; set; }
        public long AcdYearId { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
