//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_CategoryDetails
    {
        public long Invoice_Catg_Id { get; set; }
        public Nullable<long> CatgTypeId { get; set; }
        public Nullable<long> InvoiceId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ActiveStatus { get; set; }
        public string Value { get; set; }
        public Nullable<long> SelectedId { get; set; }
        public Nullable<long> schlId { get; set; }
        public string field1 { get; set; }
        public string field2 { get; set; }
        public Nullable<long> field3 { get; set; }
        public Nullable<long> field4 { get; set; }
    
        public virtual SPA_INVOICE_MASTER SPA_INVOICE_MASTER { get; set; }
    }
}
