//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language_NewShop
    {
        public long Lang_Newshop_Id { get; set; }
        public int Lang_id { get; set; }
        public string Page_Name { get; set; }
        public string Value { get; set; }
        public string English_Label { get; set; }
        public Nullable<long> Order_id { get; set; }
        public System.DateTime Created_date { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Image_Url { get; set; }
        public string col1 { get; set; }
        public string col2 { get; set; }
        public string col3 { get; set; }
        public string Catg_Sep { get; set; }
        public string Schid { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public string newdata { get; set; }
        public string MainTab { get; set; }
        public string SubTab { get; set; }
    
        public virtual Language_Master Language_Master { get; set; }
    }
}
