//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Language_Master()
        {
            this.CCTSP_CategoryDetails = new HashSet<CCTSP_CategoryDetails>();
            this.CCTSP_SchoolMaster = new HashSet<CCTSP_SchoolMaster>();
            this.CCTSP_SchoolMaster1 = new HashSet<CCTSP_SchoolMaster>();
            this.Language_Label_Detail = new HashSet<Language_Label_Detail>();
            this.Language_NewShop = new HashSet<Language_NewShop>();
        }
    
        public int Lang_id { get; set; }
        public string Lang_Name { get; set; }
        public string Country { get; set; }
        public string Currency_Symbol { get; set; }
        public string Currency { get; set; }
        public string Currency_ShortName { get; set; }
        public Nullable<int> flag { get; set; }
        public System.DateTime Created_Date { get; set; }
        public System.DateTime Updated_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_CategoryDetails> CCTSP_CategoryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_SchoolMaster> CCTSP_SchoolMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCTSP_SchoolMaster> CCTSP_SchoolMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Language_Label_Detail> Language_Label_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Language_NewShop> Language_NewShop { get; set; }
    }
}
