//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class lodhiAirVisaApp
    {
        public long ApplicationID { get; set; }
        public string ApplicantName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PassPortNumber { get; set; }
        public string Country { get; set; }
        public string ContactNo { get; set; }
        public Nullable<System.DateTime> DRS { get; set; }
        public Nullable<System.DateTime> DOR { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public string RefNo { get; set; }
        public Nullable<decimal> VisaFeeScharge { get; set; }
        public string BillNo { get; set; }
        public string VisaStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
        public string Remarks { get; set; }
        public string ActiveStatus { get; set; }
        public long Schid { get; set; }
    }
}
