//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maarkss_ClientPaymentdetails
    {
        public long ClientPaymentDetailsID { get; set; }
        public long Schid { get; set; }
        public long PaymentType { get; set; }
        public string InstrumentName { get; set; }
        public string InstrumentNo { get; set; }
        public Nullable<System.DateTime> InstrumentDate { get; set; }
        public Nullable<System.DateTime> DateofPayment { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public long AmountStatus { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
