//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maarkss_MarketingWorkSheet
    {
        public long MonthWkID { get; set; }
        public long Userid { get; set; }
        public Nullable<System.TimeSpan> Intime { get; set; }
        public Nullable<System.TimeSpan> OutTime { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> TotalManHours { get; set; }
        public string ActiveStatus { get; set; }
        public string DutyType { get; set; }
    }
}
