//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maarkss_ActivityDetails
    {
        public long ActivityDetailsId { get; set; }
        public long MonthlyWorksheetID { get; set; }
        public string Activity { get; set; }
        public Nullable<int> ManHours { get; set; }
        public string Remarks { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<long> ProjectMasterId { get; set; }
    }
}
