//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maarkss_ProjectPaymentDetails
    {
        public long ProjectPaymentDetailsID { get; set; }
        public long UserId { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<long> PeriodType { get; set; }
        public Nullable<System.DateTime> NextBillingDate { get; set; }
        public Nullable<decimal> NextAmountToBePaid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
        public long SchId { get; set; }
        public long AcdYear { get; set; }
        public Nullable<System.DateTime> ActualBillingDate { get; set; }
        public Nullable<decimal> ActualBillingAmount { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string BiilingStatus { get; set; }
        public Nullable<long> CollectionType { get; set; }
        public string InstrumentName { get; set; }
        public string InstrumentNo { get; set; }
        public Nullable<System.DateTime> InstrumentDate { get; set; }
        public Nullable<long> MemberShipID { get; set; }
        public Nullable<System.DateTime> AlertDateTime { get; set; }
        public Nullable<int> DaysDiscount { get; set; }
        public string nvarchar1 { get; set; }
        public Nullable<decimal> ndecimal { get; set; }
        public Nullable<int> nint { get; set; }
    }
}
