//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maarkss_TechDetails
    {
        public long TechDetailsID { get; set; }
        public string DomainName { get; set; }
        public string ServerFolderLocation { get; set; }
        public string SubDomain { get; set; }
        public string LastPublishSource { get; set; }
        public string TFS { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public Nullable<long> DetailsId { get; set; }
        public long SchId { get; set; }
        public string ActiveStatus { get; set; }
    }
}
