//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maarkss_ProjectMaster
    {
        public long ProjectMasterId { get; set; }
        public string ProjectName { get; set; }
        public long ProjectType { get; set; }
        public long StatusTillDate { get; set; }
        public Nullable<System.DateTime> Modifiedon { get; set; }
        public Nullable<int> TotalManHours { get; set; }
        public long EnteredBy { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExapectedDeliveryDate { get; set; }
        public Nullable<System.DateTime> ActualClosingDate { get; set; }
        public Nullable<long> Schid { get; set; }
    }
}
