//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maarkss_ProjectDetails
    {
        public long ProjectDetailsId { get; set; }
        public long ProjectMasterId { get; set; }
        public long Status { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CurrentOwner { get; set; }
        public long EnteredBy { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public int ManHoursTillDate { get; set; }
        public string ActiveStatus { get; set; }
        public string Contact_Person { get; set; }
        public string ContactNumber { get; set; }
        public string ConatctEmailId { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string FollowUpStatus { get; set; }
        public Nullable<long> Schid { get; set; }
    }
}
