//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketing_Customer
    {
        public long MCustomer_id { get; set; }
        public string first_name { get; set; }
        public string LastName { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> Updated_on { get; set; }
        public string email { get; set; }
        public string mobilenumber { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
        public Nullable<long> Extra3 { get; set; }
        public Nullable<long> Extra4 { get; set; }
    }
}
