//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketing_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marketing_Master()
        {
            this.Marketing_SendHistory = new HashSet<Marketing_SendHistory>();
        }
    
        public long MID { get; set; }
        public string Subject { get; set; }
        public string content { get; set; }
        public Nullable<long> schId { get; set; }
        public string ActiveStatus { get; set; }
        public string status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Extra_1 { get; set; }
        public string Extra_2 { get; set; }
        public string Extra_3 { get; set; }
    
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marketing_SendHistory> Marketing_SendHistory { get; set; }
    }
}
