//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketing_Group_Customer
    {
        public long M_Group_Customer_id { get; set; }
        public string Group_name { get; set; }
        public string Assign_Customer { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> Updated_on { get; set; }
        public Nullable<long> OrderData { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
        public Nullable<long> Extra3 { get; set; }
        public Nullable<long> Extra4 { get; set; }
    }
}
