//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cctspDatabaseEntities22 : DbContext
    {
        public cctspDatabaseEntities22()
            : base("name=cctspDatabaseEntities22")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Add_On_Product_Detail> Add_On_Product_Detail { get; set; }
        public virtual DbSet<Add_on_Product_Master> Add_on_Product_Master { get; set; }
        public virtual DbSet<APP_AnwserDetails> APP_AnwserDetails { get; set; }
        public virtual DbSet<APP_QuestionMaster> APP_QuestionMaster { get; set; }
        public virtual DbSet<App_UserAnserDetails> App_UserAnserDetails { get; set; }
        public virtual DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<aspnet_UsersInRoles> aspnet_UsersInRoles { get; set; }
        public virtual DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public virtual DbSet<Assigned_Health_Insurance> Assigned_Health_Insurance { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<CCTSP_AcademicYear> CCTSP_AcademicYear { get; set; }
        public virtual DbSet<CCTSP_AnswerDetails> CCTSP_AnswerDetails { get; set; }
        public virtual DbSet<CCTSP_AssgnmentHomeworkMarksDetails> CCTSP_AssgnmentHomeworkMarksDetails { get; set; }
        public virtual DbSet<CCTSP_AttendenceDetails> CCTSP_AttendenceDetails { get; set; }
        public virtual DbSet<CCTSP_AttendenceMaster> CCTSP_AttendenceMaster { get; set; }
        public virtual DbSet<CCTSP_BookIssueRegister> CCTSP_BookIssueRegister { get; set; }
        public virtual DbSet<CCTSP_CalendarDetails> CCTSP_CalendarDetails { get; set; }
        public virtual DbSet<CCTSP_CategoryDetails> CCTSP_CategoryDetails { get; set; }
        public virtual DbSet<CCTSP_CategoryMaster> CCTSP_CategoryMaster { get; set; }
        public virtual DbSet<CCTSP_ClassSection> CCTSP_ClassSection { get; set; }
        public virtual DbSet<CCTSP_ClassSubjectDetails> CCTSP_ClassSubjectDetails { get; set; }
        public virtual DbSet<CCTSP_ColorMaster> CCTSP_ColorMaster { get; set; }
        public virtual DbSet<CCTSP_Database> CCTSP_Database { get; set; }
        public virtual DbSet<CCTSP_EmployeeActivityDetails> CCTSP_EmployeeActivityDetails { get; set; }
        public virtual DbSet<CCTSP_EmployeeCurrentDetails> CCTSP_EmployeeCurrentDetails { get; set; }
        public virtual DbSet<CCTSP_EvalutionDetails> CCTSP_EvalutionDetails { get; set; }
        public virtual DbSet<CCTSP_ExamAnswerMaster> CCTSP_ExamAnswerMaster { get; set; }
        public virtual DbSet<CCTSP_Examdetails> CCTSP_Examdetails { get; set; }
        public virtual DbSet<CCTSP_ExamMaster> CCTSP_ExamMaster { get; set; }
        public virtual DbSet<CCTSP_ExamQuestionMaster> CCTSP_ExamQuestionMaster { get; set; }
        public virtual DbSet<CCTSP_FeeCollectionDetails> CCTSP_FeeCollectionDetails { get; set; }
        public virtual DbSet<CCTSP_FeeCollectionMaster> CCTSP_FeeCollectionMaster { get; set; }
        public virtual DbSet<CCTSP_FeeCollectionReciept> CCTSP_FeeCollectionReciept { get; set; }
        public virtual DbSet<CCTSP_FeeNotApplicableMaster> CCTSP_FeeNotApplicableMaster { get; set; }
        public virtual DbSet<CCTSP_FeeRuleClassSection> CCTSP_FeeRuleClassSection { get; set; }
        public virtual DbSet<CCTSP_FeeSecurityDeposit> CCTSP_FeeSecurityDeposit { get; set; }
        public virtual DbSet<CCTSP_FinancialYearDetails> CCTSP_FinancialYearDetails { get; set; }
        public virtual DbSet<CCTSP_GradeRule> CCTSP_GradeRule { get; set; }
        public virtual DbSet<CCTSP_GroupProductDetails> CCTSP_GroupProductDetails { get; set; }
        public virtual DbSet<CCTSP_HealthDetails> CCTSP_HealthDetails { get; set; }
        public virtual DbSet<CCTSP_ImageTable> CCTSP_ImageTable { get; set; }
        public virtual DbSet<CCTSP_InstallmetDetails> CCTSP_InstallmetDetails { get; set; }
        public virtual DbSet<CCTSP_ItemIssueReturnDetails> CCTSP_ItemIssueReturnDetails { get; set; }
        public virtual DbSet<CCTSP_ItemIssueSaleMaster> CCTSP_ItemIssueSaleMaster { get; set; }
        public virtual DbSet<CCTSP_ItemIssueSalesDetails> CCTSP_ItemIssueSalesDetails { get; set; }
        public virtual DbSet<CCTSP_ItemMaster> CCTSP_ItemMaster { get; set; }
        public virtual DbSet<CCTSP_ItemQtyIssueDetails> CCTSP_ItemQtyIssueDetails { get; set; }
        public virtual DbSet<CCTSP_ItemSalesBalance_PaymentDetails> CCTSP_ItemSalesBalance_PaymentDetails { get; set; }
        public virtual DbSet<CCTSP_ItemStockVerification> CCTSP_ItemStockVerification { get; set; }
        public virtual DbSet<CCTSP_ItemStoreDetails> CCTSP_ItemStoreDetails { get; set; }
        public virtual DbSet<CCTSP_ItemStoreInvoiceMaster> CCTSP_ItemStoreInvoiceMaster { get; set; }
        public virtual DbSet<CCTSP_LendingPageMaster> CCTSP_LendingPageMaster { get; set; }
        public virtual DbSet<CCTSP_LessonProgress> CCTSP_LessonProgress { get; set; }
        public virtual DbSet<CCTSP_MedicalDetails> CCTSP_MedicalDetails { get; set; }
        public virtual DbSet<CCTSP_Messaging> CCTSP_Messaging { get; set; }
        public virtual DbSet<CCTSP_ProductDetails> CCTSP_ProductDetails { get; set; }
        public virtual DbSet<CCTSP_ProductMaster> CCTSP_ProductMaster { get; set; }
        public virtual DbSet<CCTSP_Role> CCTSP_Role { get; set; }
        public virtual DbSet<cctsp_RoleDetails> cctsp_RoleDetails { get; set; }
        public virtual DbSet<CCTSP_SchedulerDetails> CCTSP_SchedulerDetails { get; set; }
        public virtual DbSet<CCTSP_SchedulerMaster> CCTSP_SchedulerMaster { get; set; }
        public virtual DbSet<CCTSP_SchoolCalender> CCTSP_SchoolCalender { get; set; }
        public virtual DbSet<CCTSP_SchoolMaster> CCTSP_SchoolMaster { get; set; }
        public virtual DbSet<cctsp_SecureIdentity> cctsp_SecureIdentity { get; set; }
        public virtual DbSet<CCTSP_StockRegisterOfLibrary> CCTSP_StockRegisterOfLibrary { get; set; }
        public virtual DbSet<CCTSP_StudentAnswerMaster> CCTSP_StudentAnswerMaster { get; set; }
        public virtual DbSet<CCTSP_StudentBatchAssociation> CCTSP_StudentBatchAssociation { get; set; }
        public virtual DbSet<CCTSP_StudentCurrentDetails> CCTSP_StudentCurrentDetails { get; set; }
        public virtual DbSet<CCTSP_StudentOptionalSubjectDetails> CCTSP_StudentOptionalSubjectDetails { get; set; }
        public virtual DbSet<CCTSP_SubjectSyllabusDetails> CCTSP_SubjectSyllabusDetails { get; set; }
        public virtual DbSet<CCTSP_TaxDetails> CCTSP_TaxDetails { get; set; }
        public virtual DbSet<CCTSP_TeacherScheduler> CCTSP_TeacherScheduler { get; set; }
        public virtual DbSet<cctsp_Timezone> cctsp_Timezone { get; set; }
        public virtual DbSet<CCTSP_TransportRouteDetails> CCTSP_TransportRouteDetails { get; set; }
        public virtual DbSet<CCTSP_User> CCTSP_User { get; set; }
        public virtual DbSet<CCTSP_UserB> CCTSP_UserB { get; set; }
        public virtual DbSet<CCTSP_UserDetail> CCTSP_UserDetail { get; set; }
        public virtual DbSet<CCTSP_UserDetails> CCTSP_UserDetails { get; set; }
        public virtual DbSet<CCTSP_VaccineDetails> CCTSP_VaccineDetails { get; set; }
        public virtual DbSet<CCTSP_Validation> CCTSP_Validation { get; set; }
        public virtual DbSet<CCTSP_ValueAddedServiceDetails> CCTSP_ValueAddedServiceDetails { get; set; }
        public virtual DbSet<CCTSP_ValueAddedServiceMaster> CCTSP_ValueAddedServiceMaster { get; set; }
        public virtual DbSet<CTSP_SolutionMaster> CTSP_SolutionMaster { get; set; }
        public virtual DbSet<DCM_AvailDetails> DCM_AvailDetails { get; set; }
        public virtual DbSet<DCm_AvailMaster> DCm_AvailMaster { get; set; }
        public virtual DbSet<DCM_Deals> DCM_Deals { get; set; }
        public virtual DbSet<DCM_PackageDetails> DCM_PackageDetails { get; set; }
        public virtual DbSet<DCM_ProductMaster> DCM_ProductMaster { get; set; }
        public virtual DbSet<Email_Record> Email_Record { get; set; }
        public virtual DbSet<GYM_DefinationMaster> GYM_DefinationMaster { get; set; }
        public virtual DbSet<GYM_Member_Dept> GYM_Member_Dept { get; set; }
        public virtual DbSet<GYM_MembershipDetails> GYM_MembershipDetails { get; set; }
        public virtual DbSet<GYM_MemeberActivityGrouping> GYM_MemeberActivityGrouping { get; set; }
        public virtual DbSet<GYM_TaxDetails> GYM_TaxDetails { get; set; }
        public virtual DbSet<GYMActivityDetail> GYMActivityDetails { get; set; }
        public virtual DbSet<Health_Insurance> Health_Insurance { get; set; }
        public virtual DbSet<Hotel_BillDetails> Hotel_BillDetails { get; set; }
        public virtual DbSet<Hotel_BillMaster> Hotel_BillMaster { get; set; }
        public virtual DbSet<Hotel_BookingDetails> Hotel_BookingDetails { get; set; }
        public virtual DbSet<Hotel_BookingMaster> Hotel_BookingMaster { get; set; }
        public virtual DbSet<Hotel_ServiceMaster> Hotel_ServiceMaster { get; set; }
        public virtual DbSet<Hotel_ServicesDetails> Hotel_ServicesDetails { get; set; }
        public virtual DbSet<Hotel_TaxDetails> Hotel_TaxDetails { get; set; }
        public virtual DbSet<Invoice_CategoryDetails> Invoice_CategoryDetails { get; set; }
        public virtual DbSet<Invoice_Master> Invoice_Master { get; set; }
        public virtual DbSet<Language_Label_Detail> Language_Label_Detail { get; set; }
        public virtual DbSet<Language_Master> Language_Master { get; set; }
        public virtual DbSet<Language_NewShop> Language_NewShop { get; set; }
        public virtual DbSet<lodhiAirVisaApp> lodhiAirVisaApps { get; set; }
        public virtual DbSet<Maarkss_ActivityDetails> Maarkss_ActivityDetails { get; set; }
        public virtual DbSet<Maarkss_ClientPaymentdetails> Maarkss_ClientPaymentdetails { get; set; }
        public virtual DbSet<Maarkss_MarketingWorkSheet> Maarkss_MarketingWorkSheet { get; set; }
        public virtual DbSet<Maarkss_ProjectDetails> Maarkss_ProjectDetails { get; set; }
        public virtual DbSet<Maarkss_ProjectMaster> Maarkss_ProjectMaster { get; set; }
        public virtual DbSet<Maarkss_ProjectPaymentDetails> Maarkss_ProjectPaymentDetails { get; set; }
        public virtual DbSet<Maarkss_TechDetails> Maarkss_TechDetails { get; set; }
        public virtual DbSet<Marketing_Customer> Marketing_Customer { get; set; }
        public virtual DbSet<Marketing_Group_Customer> Marketing_Group_Customer { get; set; }
        public virtual DbSet<Marketing_Info> Marketing_Info { get; set; }
        public virtual DbSet<Marketing_Master> Marketing_Master { get; set; }
        public virtual DbSet<Marketing_SendHistory> Marketing_SendHistory { get; set; }
        public virtual DbSet<Medicine_Master> Medicine_Master { get; set; }
        public virtual DbSet<OnlineShopping_FinancialYearDetails> OnlineShopping_FinancialYearDetails { get; set; }
        public virtual DbSet<OnlineShopping_ProductMaster> OnlineShopping_ProductMaster { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderTracking> OrderTrackings { get; set; }
        public virtual DbSet<PaymentTxnDetail> PaymentTxnDetails { get; set; }
        public virtual DbSet<Platform_Marketing_ImageList> Platform_Marketing_ImageList { get; set; }
        public virtual DbSet<Platform_Marketing_SendHistory> Platform_Marketing_SendHistory { get; set; }
        public virtual DbSet<Prescription_Detail> Prescription_Detail { get; set; }
        public virtual DbSet<Prescription_Master> Prescription_Master { get; set; }
        public virtual DbSet<ses_emp_per_porting> ses_emp_per_porting { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Shop_Address_Details> Shop_Address_Details { get; set; }
        public virtual DbSet<SPA_ActivityLog> SPA_ActivityLog { get; set; }
        public virtual DbSet<Spa_Assign_FieldDetails> Spa_Assign_FieldDetails { get; set; }
        public virtual DbSet<spa_balanceCatg> spa_balanceCatg { get; set; }
        public virtual DbSet<spa_BillingDetails> spa_BillingDetails { get; set; }
        public virtual DbSet<spa_BillingMaster> spa_BillingMaster { get; set; }
        public virtual DbSet<Spa_BookingDetails> Spa_BookingDetails { get; set; }
        public virtual DbSet<spa_contact> spa_contact { get; set; }
        public virtual DbSet<spa_currency> spa_currency { get; set; }
        public virtual DbSet<spa_CustomerFeedback> spa_CustomerFeedback { get; set; }
        public virtual DbSet<spa_DemoShop> spa_DemoShop { get; set; }
        public virtual DbSet<spa_Em_SmsLog> spa_Em_SmsLog { get; set; }
        public virtual DbSet<SPA_EmployeeScheduler> SPA_EmployeeScheduler { get; set; }
        public virtual DbSet<SPA_EmployeeSchedulers> SPA_EmployeeSchedulers { get; set; }
        public virtual DbSet<SPA_Error> SPA_Error { get; set; }
        public virtual DbSet<Spa_Flow> Spa_Flow { get; set; }
        public virtual DbSet<Spa_FlowDetails> Spa_FlowDetails { get; set; }
        public virtual DbSet<SPA_INVOICE_Detail> SPA_INVOICE_Detail { get; set; }
        public virtual DbSet<SPA_INVOICE_MASTER> SPA_INVOICE_MASTER { get; set; }
        public virtual DbSet<SPA_INVOICE_PAYMENTDETAILS> SPA_INVOICE_PAYMENTDETAILS { get; set; }
        public virtual DbSet<SPA_INVOICE_STATUS> SPA_INVOICE_STATUS { get; set; }
        public virtual DbSet<SPA_LeaveMaster> SPA_LeaveMaster { get; set; }
        public virtual DbSet<spa_Location> spa_Location { get; set; }
        public virtual DbSet<spa_Master_Reservation> spa_Master_Reservation { get; set; }
        public virtual DbSet<spa_Payment_Gateway> spa_Payment_Gateway { get; set; }
        public virtual DbSet<spa_Payment_plan> spa_Payment_plan { get; set; }
        public virtual DbSet<spa_paymentCategory> spa_paymentCategory { get; set; }
        public virtual DbSet<spa_PaymentDeduction> spa_PaymentDeduction { get; set; }
        public virtual DbSet<SPA_SchedulerSlotMaster> SPA_SchedulerSlotMaster { get; set; }
        public virtual DbSet<spa_sms> spa_sms { get; set; }
        public virtual DbSet<Spa_Table_FieldName> Spa_Table_FieldName { get; set; }
        public virtual DbSet<SPA_UserDetail> SPA_UserDetail { get; set; }
        public virtual DbSet<spa_website> spa_website { get; set; }
        public virtual DbSet<spatime_zone> spatime_zone { get; set; }
        public virtual DbSet<StockReview> StockReviews { get; set; }
        public virtual DbSet<Travel_BookingMast> Travel_BookingMast { get; set; }
        public virtual DbSet<UNI_GAS_REFUEL_DETLS> UNI_GAS_REFUEL_DETLS { get; set; }
        public virtual DbSet<UNI_ITEM_MASTER> UNI_ITEM_MASTER { get; set; }
        public virtual DbSet<UNI_ITEM_PURCHASE_DETLS> UNI_ITEM_PURCHASE_DETLS { get; set; }
        public virtual DbSet<UNI_ITEM_PURCHASE_MAST> UNI_ITEM_PURCHASE_MAST { get; set; }
        public virtual DbSet<UNI_ITEM_SALES_DETLS> UNI_ITEM_SALES_DETLS { get; set; }
        public virtual DbSet<UNI_ITEM_STORE> UNI_ITEM_STORE { get; set; }
        public virtual DbSet<UNI_PUR_TaxDetails> UNI_PUR_TaxDetails { get; set; }
        public virtual DbSet<UNI_SUPPLER_DETAILS> UNI_SUPPLER_DETAILS { get; set; }
        public virtual DbSet<V_BOOKING_MASTER> V_BOOKING_MASTER { get; set; }
        public virtual DbSet<V_Recpit_BillMaster> V_Recpit_BillMaster { get; set; }
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public virtual DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<CCTSP_ABC> CCTSP_ABC { get; set; }
        public virtual DbSet<CCTSP_values> CCTSP_values { get; set; }
        public virtual DbSet<CCTSP_Anamnese> CCTSP_Anamnese { get; set; }
    }
}
