//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineShopping_FinancialYearDetails
    {
        public long FinacialYearId { get; set; }
        public long SchID { get; set; }
        public long AcdYear { get; set; }
        public long ProductMasterID { get; set; }
        public Nullable<int> OpeningBal { get; set; }
        public Nullable<int> TotalRecieve { get; set; }
        public Nullable<int> TotalIssueSales { get; set; }
        public Nullable<int> DamageStock { get; set; }
        public Nullable<int> CurrentStock { get; set; }
        public Nullable<int> ClosingBal { get; set; }
        public decimal SalesPrice { get; set; }
        public Nullable<decimal> SalesPricePercentage { get; set; }
        public string RecordStatus { get; set; }
    }
}
