//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineShopping_ProductMaster
    {
        public long ProductMasterId { get; set; }
        public Nullable<long> ItemColorCatgID { get; set; }
        public Nullable<long> ItemSolutionFabricId { get; set; }
        public Nullable<long> ItemSolutionOccsionID { get; set; }
        public Nullable<long> ItemSolutionCatgID { get; set; }
        public Nullable<long> UnitCatgId { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<int> Size { get; set; }
        public string ItemDescription { get; set; }
        public string ItemRemarks { get; set; }
        public Nullable<long> StoreSolutionID { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string ItemCode { get; set; }
        public string Itemdetails1 { get; set; }
        public string ItemDetails2 { get; set; }
        public string ItemDetails3 { get; set; }
        public long Schid { get; set; }
        public string ActiveStatus { get; set; }
        public long ItemProductNameSolutionID { get; set; }
        public Nullable<decimal> ActualSalePrice { get; set; }
        public Nullable<decimal> PurPrice { get; set; }
        public Nullable<int> OBal { get; set; }
        public Nullable<int> closebal { get; set; }
        public Nullable<int> TRecive { get; set; }
        public Nullable<int> TotalSale { get; set; }
        public Nullable<int> CurrentStock { get; set; }
        public string logostate { get; set; }
        public Nullable<long> PublishedBy { get; set; }
        public Nullable<long> EnteredBy { get; set; }
    }
}
