//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTracking
    {
        public long OrderTrackId { get; set; }
        public string ShippingType { get; set; }
        public string CompanyName { get; set; }
        public string Description { get; set; }
        public string PackageCode { get; set; }
        public int PackageQueue { get; set; }
        public string CompanyTrackID { get; set; }
        public string ActiveStatus { get; set; }
        public long Schid { get; set; }
        public string ShippingStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long OrderID { get; set; }
        public string Remarks { get; set; }
    }
}
