//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTxnDetail
    {
        public long PaymentTxnID { get; set; }
        public long TxnType { get; set; }
        public string InstrumentName { get; set; }
        public Nullable<long> InstrumentNo { get; set; }
        public Nullable<System.DateTime> InstrumentDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TxnStatus { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long OrderID { get; set; }
        public long Schid { get; set; }
        public string TxnID { get; set; }
        public Nullable<int> int1 { get; set; }
        public string nvarchar1 { get; set; }
        public Nullable<long> bigint1 { get; set; }
        public string reqTxnStatus { get; set; }
        public string reqTxnID { get; set; }
        public string ReqPaymentId { get; set; }
        public string reqTxnRefNo { get; set; }
        public string reqTxnError { get; set; }
        public string ReqAuth { get; set; }
    }
}
