//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platform_Marketing_SendHistory
    {
        public long M_Send_History_id { get; set; }
        public long MInfo_id { get; set; }
        public string ActiveStatus { get; set; }
        public string status { get; set; }
        public System.DateTime SendDate { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
        public string Extra3 { get; set; }
        public string GroupUserId { get; set; }
    
        public virtual Marketing_Info Marketing_Info { get; set; }
    }
}
