//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prescription_Master()
        {
            this.Medicine_Master = new HashSet<Medicine_Master>();
            this.Prescription_Detail = new HashSet<Prescription_Detail>();
        }
    
        public long Prescription_Id { get; set; }
        public long UserId { get; set; }
        public System.DateTime created_on { get; set; }
        public int BookingId { get; set; }
        public Nullable<int> Diff { get; set; }
        public string Extra { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<long> SchId { get; set; }
        public Nullable<long> MasterResId { get; set; }
    
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster { get; set; }
        public virtual CCTSP_User CCTSP_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicine_Master> Medicine_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription_Detail> Prescription_Detail { get; set; }
        public virtual SPA_EmployeeScheduler SPA_EmployeeScheduler { get; set; }
        public virtual spa_Master_Reservation spa_Master_Reservation { get; set; }
    }
}
