//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ses_emp_per_porting
    {
        public int id { get; set; }
        public System.DateTime dnt { get; set; }
        public string Excel { get; set; }
        public string sqltable { get; set; }
        public string status { get; set; }
        public string startrow { get; set; }
        public string remark { get; set; }
    }
}
