//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Address_Details
    {
        public long Shop_Address_Id { get; set; }
        public string ShopName { get; set; }
        public string Strret { get; set; }
        public string PostCode { get; set; }
        public string Location { get; set; }
        public string StateShortName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ActiveStatus { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
        public string field1 { get; set; }
        public string field2 { get; set; }
        public Nullable<long> field3 { get; set; }
        public Nullable<long> field4 { get; set; }
        public string FullName { get; set; }
        public string Methods { get; set; }
    }
}
