//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class spa_BillingMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public spa_BillingMaster()
        {
            this.spa_BillingDetails = new HashSet<spa_BillingDetails>();
        }
    
        public long Receipt_Id { get; set; }
        public long ShopId { get; set; }
        public double TotalAmount { get; set; }
        public string ActiveStatus { get; set; }
        public int country_id { get; set; }
        public Nullable<double> TotalCredit { get; set; }
        public System.DateTime created_on { get; set; }
        public System.DateTime Updated_on { get; set; }
        public string DurationStatus { get; set; }
        public string Duration { get; set; }
        public double RemainingCredit { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spa_BillingDetails> spa_BillingDetails { get; set; }
        public virtual spatime_zone spatime_zone { get; set; }
    }
}
