//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class spa_Master_Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public spa_Master_Reservation()
        {
            this.Medicine_Master = new HashSet<Medicine_Master>();
            this.Prescription_Detail = new HashSet<Prescription_Detail>();
            this.Prescription_Master = new HashSet<Prescription_Master>();
            this.spa_CustomerFeedback = new HashSet<spa_CustomerFeedback>();
            this.SPA_EmployeeScheduler = new HashSet<SPA_EmployeeScheduler>();
        }
    
        public long MasterResId { get; set; }
        public Nullable<long> EmpId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<double> TotalTime { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string ActiveStatus { get; set; }
        public string BookedStatus { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
        public string IP { get; set; }
        public string BookingDate { get; set; }
        public string Reg_Status { get; set; }
        public string ProductId_list { get; set; }
        public string Comment { get; set; }
        public Nullable<long> Schlid { get; set; }
        public string FeedBack_Comment { get; set; }
        public Nullable<int> Paystatus { get; set; }
        public Nullable<long> Created_By { get; set; }
    
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicine_Master> Medicine_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription_Detail> Prescription_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription_Master> Prescription_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spa_CustomerFeedback> spa_CustomerFeedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_EmployeeScheduler> SPA_EmployeeScheduler { get; set; }
    }
}
