//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class spa_currency
    {
        public int currency_id { get; set; }
        public string name_country { get; set; }
        public string currency { get; set; }
        public string ActiveStatus { get; set; }
    }
}
