//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class spa_sms
    {
        public int sms_id { get; set; }
        public string sms_url { get; set; }
        public string country { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime created_date { get; set; }
    }
}
