//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPA_INVOICE_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPA_INVOICE_MASTER()
        {
            this.Invoice_CategoryDetails = new HashSet<Invoice_CategoryDetails>();
            this.SPA_INVOICE_Detail = new HashSet<SPA_INVOICE_Detail>();
            this.SPA_INVOICE_STATUS = new HashSet<SPA_INVOICE_STATUS>();
            this.SPA_INVOICE_PAYMENTDETAILS = new HashSet<SPA_INVOICE_PAYMENTDETAILS>();
        }
    
        public long Invoice_Id { get; set; }
        public string Invoice_Status { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long SchlId { get; set; }
        public long CustomerId { get; set; }
        public long EmployeeId { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public Nullable<long> Field1 { get; set; }
        public Nullable<long> field2 { get; set; }
        public string field3 { get; set; }
        public string field4 { get; set; }
        public Nullable<System.DateTime> Paid_Date { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> Reminderdate1 { get; set; }
        public Nullable<System.DateTime> Reminderdate2 { get; set; }
        public Nullable<System.DateTime> Reminderdate3 { get; set; }
        public Nullable<System.DateTime> Reminderdate4 { get; set; }
        public string Image_barcode { get; set; }
        public Nullable<double> Total_Amount { get; set; }
        public Nullable<double> Remaining_Amount { get; set; }
    
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster { get; set; }
        public virtual CCTSP_User CCTSP_User { get; set; }
        public virtual CCTSP_User CCTSP_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_CategoryDetails> Invoice_CategoryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_INVOICE_Detail> SPA_INVOICE_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_INVOICE_STATUS> SPA_INVOICE_STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_INVOICE_PAYMENTDETAILS> SPA_INVOICE_PAYMENTDETAILS { get; set; }
    }
}
