//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class spa_website
    {
        public long website_id { get; set; }
        public string website_url { get; set; }
        public string servername { get; set; }
        public string Activestatus { get; set; }
        public Nullable<long> schid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string col1 { get; set; }
        public string col2 { get; set; }
        public string col3 { get; set; }
        public string col4 { get; set; }
        public string col5 { get; set; }
    }
}
