//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class spa_balanceCatg
    {
        public long bal_catgId { get; set; }
        public string bal_catgName { get; set; }
        public System.DateTime bal_createdDate { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime bal_updatedDate { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
    }
}
