//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPA_INVOICE_PAYMENTDETAILS
    {
        public long Invoice_Payment_Id { get; set; }
        public long Invoice_Id { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public long SchlId { get; set; }
        public Nullable<System.DateTime> Pay_Date { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<long> Field1 { get; set; }
        public Nullable<long> field2 { get; set; }
        public string field3 { get; set; }
        public string field4 { get; set; }
        public Nullable<System.DateTime> Field5 { get; set; }
        public Nullable<double> Discount_Amount { get; set; }
        public Nullable<int> Payment_Catg { get; set; }
        public Nullable<double> Pay_Amount { get; set; }
    
        public virtual SPA_INVOICE_MASTER SPA_INVOICE_MASTER { get; set; }
    }
}
