//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class spa_CustomerFeedback
    {
        public long Feedback_id { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Reservation_id { get; set; }
        public Nullable<long> CatgTypeId { get; set; }
        public string Rating { get; set; }
        public string Feedback1 { get; set; }
        public string Feedback2 { get; set; }
        public string Feedback3 { get; set; }
        public Nullable<long> MasterResId { get; set; }
    
        public virtual CCTSP_CategoryDetails CCTSP_CategoryDetails { get; set; }
        public virtual spa_Master_Reservation spa_Master_Reservation { get; set; }
        public virtual SPA_EmployeeScheduler SPA_EmployeeScheduler { get; set; }
    }
}
