//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class spa_PaymentDeduction
    {
        public int Deduction_id { get; set; }
        public string CatgName { get; set; }
        public string DeductionAmount { get; set; }
        public string ActiveStatus { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Country_id { get; set; }
        public string CatgKey { get; set; }
        public Nullable<int> PaymentCatgId { get; set; }
    
        public virtual spa_paymentCategory spa_paymentCategory { get; set; }
        public virtual spatime_zone spatime_zone { get; set; }
    }
}
