//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPA_Error
    {
        public long ErrorId { get; set; }
        public string Controller_name { get; set; }
        public string Action_Name { get; set; }
        public string ErrorMsg { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string ReqColumn1 { get; set; }
        public string ReqColumn2 { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
        public string Extra3 { get; set; }
        public string Extra4 { get; set; }
    }
}
