//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spa_Assign_FieldDetails
    {
        public long FieldDetail_Id { get; set; }
        public Nullable<long> Field_Id { get; set; }
        public Nullable<long> Flow_Id { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Extra_1 { get; set; }
        public string Extra_2 { get; set; }
        public string Extra_3 { get; set; }
        public string Extra_4 { get; set; }
    
        public virtual Spa_Table_FieldName Spa_Table_FieldName { get; set; }
        public virtual Spa_Flow Spa_Flow { get; set; }
    }
}
