//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPA_EmployeeSchedulers
    {
        public long Scheduler_Time_Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public long SchId { get; set; }
        public string WeekDay { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> PeriodNumber { get; set; }
        public string PeriodType { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<long> AcdYearId { get; set; }
        public Nullable<int> TimeDiff { get; set; }
        public Nullable<long> SchedulerId { get; set; }
    
        public virtual CCTSP_AcademicYear CCTSP_AcademicYear { get; set; }
        public virtual CCTSP_SchedulerMaster CCTSP_SchedulerMaster { get; set; }
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster { get; set; }
        public virtual CCTSP_User CCTSP_User { get; set; }
    }
}
