//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPA_ActivityLog
    {
        public long ActivityId { get; set; }
        public string Controller_name { get; set; }
        public string Action_Name { get; set; }
        public string Activity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> schlId { get; set; }
        public string Your_Name { get; set; }
        public string ReqColumn1 { get; set; }
        public string ReqColumn2 { get; set; }
        public string ReqColumn3 { get; set; }
        public string ReqColumn4 { get; set; }
    }
}
