//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPA_EmployeeScheduler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPA_EmployeeScheduler()
        {
            this.Medicine_Master = new HashSet<Medicine_Master>();
            this.Prescription_Detail = new HashSet<Prescription_Detail>();
            this.Prescription_Master = new HashSet<Prescription_Master>();
            this.spa_BillingDetails = new HashSet<spa_BillingDetails>();
            this.Spa_BookingDetails = new HashSet<Spa_BookingDetails>();
            this.spa_CustomerFeedback = new HashSet<spa_CustomerFeedback>();
            this.spa_Em_SmsLog = new HashSet<spa_Em_SmsLog>();
            this.SPA_INVOICE_Detail = new HashSet<SPA_INVOICE_Detail>();
        }
    
        public int EmpSchDetailsId { get; set; }
        public string FromSlotMasterId { get; set; }
        public string BookingDate { get; set; }
        public string ToSlotMasterId { get; set; }
        public Nullable<long> SchedulerId { get; set; }
        public Nullable<long> EMP_UserId { get; set; }
        public Nullable<long> CLIENT_UserId { get; set; }
        public Nullable<long> Product_Id { get; set; }
        public string Product_price { get; set; }
        public string BookedStatus { get; set; }
        public Nullable<long> SchId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string reg_status { get; set; }
        public Nullable<long> Rem_Sms { get; set; }
        public string DeclinedStatus { get; set; }
        public Nullable<System.DateTime> Date_time_Rem { get; set; }
        public Nullable<int> Reminder_hours { get; set; }
        public string Comment { get; set; }
        public Nullable<long> MasterResId { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<long> Invoice_Id { get; set; }
    
        public virtual CCTSP_CategoryDetails CCTSP_CategoryDetails { get; set; }
        public virtual CCTSP_SchedulerMaster CCTSP_SchedulerMaster { get; set; }
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster { get; set; }
        public virtual Invoice_Master Invoice_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicine_Master> Medicine_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription_Detail> Prescription_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription_Master> Prescription_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spa_BillingDetails> spa_BillingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spa_BookingDetails> Spa_BookingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spa_CustomerFeedback> spa_CustomerFeedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spa_Em_SmsLog> spa_Em_SmsLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_INVOICE_Detail> SPA_INVOICE_Detail { get; set; }
        public virtual spa_Master_Reservation spa_Master_Reservation { get; set; }
    }
}
