//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class spa_contact
    {
        public long contact_id { get; set; }
        public string FirstName { get; set; }
        public string Street { get; set; }
        public string place { get; set; }
        public string Email { get; set; }
        public string Firm { get; set; }
        public string plz { get; set; }
        public string Mobile { get; set; }
        public string communication { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Activestatus { get; set; }
        public long schid { get; set; }
        public string Title { get; set; }
        public string Col1 { get; set; }
        public string col2 { get; set; }
    
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster { get; set; }
    }
}
