//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class spa_Payment_plan
    {
        public long PaymentDetail_Id { get; set; }
        public Nullable<int> PaymentCatgId { get; set; }
        public Nullable<double> quantity_or_price { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<int> country_id { get; set; }
        public string Calculation { get; set; }
        public Nullable<double> Percharge { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> Updated_on { get; set; }
        public Nullable<int> daysconsider { get; set; }
        public string Source { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
    
        public virtual spatime_zone spatime_zone { get; set; }
        public virtual spa_paymentCategory spa_paymentCategory { get; set; }
    }
}
