//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class spa_paymentCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public spa_paymentCategory()
        {
            this.spa_BillingDetails = new HashSet<spa_BillingDetails>();
            this.spa_Payment_plan = new HashSet<spa_Payment_plan>();
            this.spa_PaymentDeduction = new HashSet<spa_PaymentDeduction>();
        }
    
        public int PaymentCatgId { get; set; }
        public string PaymentCatgName { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime created_date { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public string Where_To_display { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spa_BillingDetails> spa_BillingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spa_Payment_plan> spa_Payment_plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spa_PaymentDeduction> spa_PaymentDeduction { get; set; }
    }
}
