//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class spa_BillingDetails
    {
        public long BillColId { get; set; }
        public long ReceiptId { get; set; }
        public double Amount { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<double> Credit { get; set; }
        public System.DateTime created_on { get; set; }
        public System.DateTime Updated_on { get; set; }
        public string DurationStatus { get; set; }
        public string Duration { get; set; }
        public double receivedAmount { get; set; }
        public long ShopId { get; set; }
        public Nullable<int> ReservationId { get; set; }
        public Nullable<int> RechargeId { get; set; }
    
        public virtual CCTSP_SchoolMaster CCTSP_SchoolMaster { get; set; }
        public virtual spa_paymentCategory spa_paymentCategory { get; set; }
        public virtual spa_BillingMaster spa_BillingMaster { get; set; }
        public virtual SPA_EmployeeScheduler SPA_EmployeeScheduler { get; set; }
    }
}
