//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class spa_Payment_Gateway
    {
        public long PaymentGatewayId { get; set; }
        public string key { get; set; }
        public string txnid_ { get; set; }
        public string amount_ { get; set; }
        public string productinfo { get; set; }
        public string firstname_ { get; set; }
        public string ActiveStatus { get; set; }
        public string lastname_ { get; set; }
        public string email_ { get; set; }
        public string phone { get; set; }
        public string surl { get; set; }
        public string furl { get; set; }
        public string hash { get; set; }
        public string service_provider { get; set; }
        public string udf1 { get; set; }
        public Nullable<int> online { get; set; }
        public Nullable<int> field1 { get; set; }
        public Nullable<int> field2 { get; set; }
        public string field3 { get; set; }
        public string field4 { get; set; }
        public Nullable<long> Schlid { get; set; }
        public Nullable<long> UserId { get; set; }
        public string TableName { get; set; }
        public string PriceList { get; set; }
        public string PaymentReason { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    }
}
