//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockReview
    {
        public long StockReviewID { get; set; }
        public long ItemID { get; set; }
        public int StockAmount { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long Schid { get; set; }
        public long EnterBY { get; set; }
        public string Remarks { get; set; }
        public string StockReviewType { get; set; }
    }
}
