//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNI_ITEM_SALES_DETLS
    {
        public long ITEM_SALES_CODE_DETLS { get; set; }
        public long ITEM_CODE { get; set; }
        public long SALES_QTY { get; set; }
        public string IID1 { get; set; }
        public string IID2 { get; set; }
        public string IID3 { get; set; }
        public string MakeDetails { get; set; }
        public string BatchNo { get; set; }
        public Nullable<long> OPENING_MEATER_READING { get; set; }
        public Nullable<long> CLOSING_MEATER_READING { get; set; }
        public Nullable<long> REMARKS { get; set; }
        public Nullable<System.DateTime> SALES_Date { get; set; }
        public Nullable<long> TotalAmount { get; set; }
        public Nullable<long> TotalDiscount { get; set; }
        public Nullable<long> UNIT_COST { get; set; }
        public long Schid { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> UPDATED_BY { get; set; }
        public string Pstatus { get; set; }
        public string BCStatus { get; set; }
        public string BankName { get; set; }
        public string BankTransID { get; set; }
        public string BankInstNO { get; set; }
        public Nullable<System.DateTime> BankInstDate { get; set; }
    }
}
