//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNI_SUPPLER_DETAILS
    {
        public long SUPPLER_DET_ID { get; set; }
        public long SUPPLER_SCH_ID { get; set; }
        public string B140 { get; set; }
        public Nullable<long> BI1 { get; set; }
        public Nullable<long> BI2 { get; set; }
        public Nullable<long> BI3 { get; set; }
        public string B1200 { get; set; }
        public long SchidGroup { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Activestatus { get; set; }
    }
}
