//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNI_ITEM_PURCHASE_DETLS
    {
        public long ITEM_PURCHASE_CODE_DETLS { get; set; }
        public long ITEM_PURCHASE_CODE_MAST { get; set; }
        public long ITEM_CODE { get; set; }
        public long PURCHASE_QTY { get; set; }
        public string CN_CetaneNumber { get; set; }
        public string CN_Density { get; set; }
        public string CN_lubricity { get; set; }
        public string cold_flow { get; set; }
        public string PH { get; set; }
        public string MakeDetails { get; set; }
        public string BatchNo { get; set; }
        public Nullable<System.DateTime> Make_Date { get; set; }
        public Nullable<System.DateTime> Exp_Date { get; set; }
        public Nullable<long> TotalAmount { get; set; }
        public Nullable<long> TotalDiscount { get; set; }
        public Nullable<long> UNIT_COST { get; set; }
        public long Schid { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> UPDATED_BY { get; set; }
        public string Pstatus { get; set; }
    }
}
