//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNI_PUR_TaxDetails
    {
        public long TaxId { get; set; }
        public long PUR_CODE { get; set; }
        public long PUR_DET_CODE { get; set; }
        public long ServiceCatgType { get; set; }
        public Nullable<decimal> PerTax { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long Schid { get; set; }
        public Nullable<long> AcdYear { get; set; }
        public string R1 { get; set; }
    }
}
