//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNI_ITEM_STORE
    {
        public long ITEM_STORE_ID { get; set; }
        public long ITEM_CODE { get; set; }
        public string STORE_NAME { get; set; }
        public Nullable<long> ITEM_OPENING_BALANCE { get; set; }
        public Nullable<long> ITEM_PURCHASED_QTY { get; set; }
        public Nullable<long> ITEM_ISSUE_QTY { get; set; }
        public Nullable<long> ITEM_SALE_QTY { get; set; }
        public Nullable<long> ITEM_BALANCE { get; set; }
        public Nullable<long> ITEM_REORDER_LEVEL { get; set; }
        public long Schid { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Activestatus { get; set; }
    }
}
