//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNI_ITEM_PURCHASE_MAST
    {
        public long ITEM_PURCHASE_CODE_MAST { get; set; }
        public System.DateTime PURCHASE_DATE { get; set; }
        public string ChallanNumber { get; set; }
        public Nullable<System.DateTime> ChallanNumber_Date { get; set; }
        public string InvoiceNO { get; set; }
        public Nullable<System.DateTime> InvoiceNO_Date { get; set; }
        public Nullable<long> TotalAmount { get; set; }
        public Nullable<long> TotalDiscount { get; set; }
        public string PURCHASE_REMARKS { get; set; }
        public long Schid { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> UPDATED_BY { get; set; }
        public string Pstatus { get; set; }
        public Nullable<long> SupplerID { get; set; }
        public string ItemB1 { get; set; }
        public string ItemCatID { get; set; }
        public Nullable<long> ItemBI1 { get; set; }
    }
}
