//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNI_ITEM_MASTER
    {
        public long ITEM_CODE { get; set; }
        public long ITEM_CAT_DESC { get; set; }
        public long ITEM_CAT_UOM { get; set; }
        public long ITEM_CAT_TYPE { get; set; }
        public Nullable<long> linkID { get; set; }
        public Nullable<long> PurchaseCost { get; set; }
        public Nullable<long> CurrentValue { get; set; }
        public string BatchNO { get; set; }
        public string MakeDetails { get; set; }
        public long Schid { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Activestatus { get; set; }
        public string ITEM_NAME { get; set; }
        public Nullable<long> ITEM_SALES_PRICE { get; set; }
    }
}
