//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BOOKING_MASTER
    {
        public long V_BOOKINGID { get; set; }
        public System.DateTime BOOKING_DATE { get; set; }
        public Nullable<long> COMPANY_SCH_ID { get; set; }
        public Nullable<long> VEHICLE_CAB_TYPE { get; set; }
        public Nullable<long> VEHICLE_ID { get; set; }
        public string REPORTING_ADDRESS { get; set; }
        public string SIM_TIMMING { get; set; }
        public string REPORTING_TIME { get; set; }
        public Nullable<long> DriverUID { get; set; }
        public Nullable<long> CLIENT_USER_ID { get; set; }
        public Nullable<long> STARTING_MEATER_READING { get; set; }
        public Nullable<long> CLOSING_MEATER_READING { get; set; }
        public Nullable<long> TOTAL_KMS { get; set; }
        public Nullable<long> EXTRA_KMS { get; set; }
        public Nullable<decimal> EXTRA_KMS_CHARGES { get; set; }
        public string STARTING_TIMMING { get; set; }
        public string CLOSING_TIMMING { get; set; }
        public Nullable<decimal> TOTAL_HOURS { get; set; }
        public Nullable<decimal> EXTRA_HOURS { get; set; }
        public Nullable<decimal> EXTRA_HOURS_CHARGES { get; set; }
        public string PARTICULAR { get; set; }
        public Nullable<long> TARIFF_CAT_TYPE { get; set; }
        public Nullable<decimal> EXTRA_KMS_CHARGES_AMT { get; set; }
        public Nullable<decimal> EXTRA_HOURS_CHARGES_AMT { get; set; }
        public Nullable<decimal> NIGHT_CHARGES_AMT { get; set; }
        public Nullable<decimal> PARKING_CHARGES_AMT { get; set; }
        public Nullable<decimal> OTHER_CHARGES_AMT { get; set; }
        public string OTHER_CHARGES_AMT_REMARKS { get; set; }
        public Nullable<decimal> Total_TAX_Amount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public string OWNER_VENDER_FLG { get; set; }
        public Nullable<long> INVOICE_NO { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public string VENDOR_Name { get; set; }
        public string VENDOR_DRIVER_Name { get; set; }
        public string VENDOR_VEHICLE_NO { get; set; }
        public string VENDOR_REMARKS { get; set; }
        public long Schid { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> UPDATED_BY { get; set; }
        public string Pstatus { get; set; }
        public string BCStatus_BANK_CASH { get; set; }
        public string BankName { get; set; }
        public string BankTransID { get; set; }
        public string BankInstNO { get; set; }
        public Nullable<System.DateTime> BankInstDate { get; set; }
        public Nullable<decimal> TotalAmount_PAID { get; set; }
        public Nullable<decimal> ADVANCE_AMT_PAID { get; set; }
        public Nullable<decimal> BALANCE_Amount_TO_COLLECT { get; set; }
        public Nullable<decimal> Total_VENDER_Amount { get; set; }
        public Nullable<decimal> Total_VENDER_Amount_PAID { get; set; }
        public Nullable<decimal> BALANCE_VENDER_Amount_TO_PAY { get; set; }
        public Nullable<long> SERVICE_FEEDBACK_POINT { get; set; }
        public string Status_BANK { get; set; }
        public Nullable<long> NIGHT_STAY { get; set; }
        public Nullable<long> Other_1 { get; set; }
        public Nullable<long> Other_2 { get; set; }
        public string Other_2T { get; set; }
        public string Other_5T { get; set; }
        public string Other_10T { get; set; }
        public string Cname { get; set; }
        public string Cname1 { get; set; }
        public string CnameType { get; set; }
        public Nullable<decimal> OtherDec1 { get; set; }
        public Nullable<decimal> OtherDec2 { get; set; }
        public Nullable<decimal> OtherDec3 { get; set; }
        public Nullable<long> Other3 { get; set; }
        public string Other3T2 { get; set; }
        public string Other3T1 { get; set; }
    }
}
