//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Recpit_BillMaster
    {
        public long BillMasterID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> InvNo { get; set; }
        public Nullable<long> CompID { get; set; }
        public string RecieptNo { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Discount_Remarks { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<long> PaymentType { get; set; }
        public Nullable<int> InNUM { get; set; }
        public string InName { get; set; }
        public Nullable<System.DateTime> Indate { get; set; }
        public string RollbackStatus { get; set; }
        public string Remarks { get; set; }
        public int PrintCount { get; set; }
        public long SchId { get; set; }
        public long AcdYearId { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
    }
}
